### ISSUE TITLE
Support LD logging command output for detecting users that change alarm state

### ISSUE THREAD

**Issue by gjbadros** [gwww/elkm1#12]
See also (now-closed) https://github.com/home-assistant/core/issues/35310

The LD message type should be handled so we can reliably report which user armed/disarmed/whatever a given area. This then needs to get supported by Home Assistant's elk module which right now assumes the area changed is the last one that saw an interaction (which is often not the case in a multi-area setup).

@gwww do you want me to take the first stab at this implementation?

**Comment by gwww** [comment]
Sure.

**Comment by gjbadros** [comment]
Just sent you the PR.

**Comment by gjbadros** [comment]
Thanks -- hass PR is https://github.com/home-assistant/core/pull/36211
