### ISSUE TITLE
Counters not updated

### ISSUE THREAD

**Issue by HerveB** [gwww/elkm1#14]
Is there a way to refresh the counters? It seems the counters are updated only when the integration starts in Home Assistant.

**Comment by gwww** [comment]
There is no way that I know of of refreshing the counter when it is changed through some mechanism outside of this library. There is no notification that it has changed. 

The only thing possible is to add a function to that HASS could invoke to retrieve the current value of a counter. Is that useful for your use case?

**Comment by HerveB** [comment]
Thanks for your response. That would work. I don't need to trigger anything when the counter changes so a call to a function (exposed as a service in HA?) is perfectly fine for my use case.

**Comment by gwww** [comment]
Yes, it would be a service in HA.

**Comment by HerveB** [comment]
This would be great!

**Comment by gwww** [comment]
ElkM1 library code written. HA code to be completed. Will link HA PR here when submitted.

**Comment by HerveB** [comment]
Thanks so much!

**Comment by gwww** [comment]
PR submitted to HA. https://github.com/home-assistant/core/pull/41867

**Comment by gwww** [comment]
PR merged; will be in next HA release (docs are lagging behind and may miss next release).
