### ISSUE TITLE
Requirement is pinned for elkm1-lib 0.7.18: pytz>=2018.9,<2019.0

### ISSUE THREAD

**Issue by MartinHjelmare** [gwww/elkm1#15]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by gwww** [comment]
Fixed. Bumped lib version to 0.7.19. Home Assistant PR https://github.com/home-assistant/core/pull/38368

**Comment by MartinHjelmare** [comment]
Thanks! It would be good to update the github source here and release the version also on github.

**Comment by gwww** [comment]
All done! Thx for the reminder.
