### ISSUE TITLE
Document the trouble statuses

### ISSUE THREAD

**Issue by gwww** [gwww/elkm1#17]
There are no docs for how the ElkM1 trouble statuses can be used for automation.

See https://community.home-assistant.io/t/elk-m1-interface/4461/830 and https://community.home-assistant.io/t/elk-m1-interface/4461/831

**Comment by RichardUUU** [comment]
Yes!

**Comment by gwww** [comment]
https://github.com/home-assistant/home-assistant.io/pull/14707

(Will close when PR merged)

**Comment by gwww** [comment]
PR merged. New docs visible on HA doc site.
