### ISSUE TITLE
Missing module pytest, imported by test_message.py

### ISSUE THREAD

**Issue by cyberdot49** [gwww/elkm1#2]
In test_message.py,   the import pytest fails as there is no module named pytest

**Comment by gwww** [comment]
The dev dependencies are not installed. I use ```pipenv``` with this project. To install in developer mode use:

```
pipenv install -e .
pipenv install --dev
```

```pipenv``` may have to be installed first.

**Comment by cyberdot49** [comment]
Glenn, 

Thank you,

Dan

**Comment by gwww** [comment]
Added "Development" section to README.
