### ISSUE TITLE
Keypad KeyChange Update (KC/kf)

### ISSUE THREAD

**Issue by gwww** [gwww/elkm1#21]
Nothing yet for these but it would be cool to be able to use the Elk keypad as an interface to HA. This would also allow changes to chime

See https://community.home-assistant.io/t/elk-m1-interface/4461/813

**Comment by gwww** [comment]
Support for KC being added. Other messages can be added through separate enhancement request if they are desired.

**Comment by gwww** [comment]
PR submitted to HA. https://github.com/home-assistant/core/pull/41867

**Comment by gwww** [comment]
PR merged; will be in next HA release (docs are lagging behind and may miss next release).

An `elkm1.keypad_keypress_key` event is generated in HA when a key pressed on ElkM1 keypad.

**Comment by jimboca** [comment]
I'm using keypress events and that works great, but I'm not able to figure out how this allows reading current chime or changing it?
