### ISSUE TITLE
Request - Allow setting system time (rw)

### ISSUE THREAD

**Issue by wuench** [gwww/elkm1#23]
Would be nice to be able to set the time from HASS.  A lot of Elk firmware releases were plagued with DST bugs, including the one I have to remain on to support my wireless module.

**Comment by gwww** [comment]
I'm adding the rw support now. Plan is from HA to allow to only use the current time on the HA platform to set the time. Thoughts?

**Comment by wuench** [comment]
Syncing current system time would work for me.

**Comment by gwww** [comment]
PR submitted to HA. https://github.com/home-assistant/core/pull/41867

**Comment by gwww** [comment]
PR merged; will be in next HA release (docs are lagging behind and may miss next release).
