### ISSUE TITLE
Alarm State Not Correct

### ISSUE THREAD

**Issue by mstarks01** [gwww/elkm1#24]
I used Node Red to set the alarm to night instant every night, and disarm it in the morning. That works; however, the state in HA does not change from armed_night *unless* I connect and disconnect with ElkRP.

Here's my Node Red config.
`[{"id":"46098a97.857bd4","type":"light-scheduler","z":"e273cd4b.ee175","settings":"246f4de5.1a9b02","events":"[{\"start\":{\"dow\":1,\"mod\":1320},\"end\":{\"dow\":2,\"mod\":0}},{\"start\":{\"dow\":2,\"mod\":1320},\"end\":{\"dow\":3,\"mod\":0}},{\"start\":{\"dow\":3,\"mod\":1320},\"end\":{\"dow\":4,\"mod\":0}},{\"start\":{\"dow\":4,\"mod\":1320},\"end\":{\"dow\":5,\"mod\":0}},{\"start\":{\"dow\":5,\"mod\":1320},\"end\":{\"dow\":6,\"mod\":0}},{\"start\":{\"dow\":6,\"mod\":1320},\"end\":{\"dow\":0,\"mod\":0}},{\"start\":{\"dow\":0,\"mod\":1320},\"end\":{\"dow\":1,\"mod\":0}},{\"start\":{\"dow\":1,\"mod\":0},\"end\":{\"dow\":1,\"mod\":420}},{\"start\":{\"dow\":2,\"mod\":0},\"end\":{\"dow\":2,\"mod\":420}},{\"start\":{\"dow\":3,\"mod\":0},\"end\":{\"dow\":3,\"mod\":420}},{\"start\":{\"dow\":4,\"mod\":0},\"end\":{\"dow\":4,\"mod\":420}},{\"start\":{\"dow\":5,\"mod\":0},\"end\":{\"dow\":5,\"mod\":420}},{\"start\":{\"dow\":6,\"mod\":0},\"end\":{\"dow\":6,\"mod\":420}},{\"start\":{\"dow\":0,\"mod\":0},\"end\":{\"dow\":0,\"mod\":420}}]","topic":"","name":"Night Schedule","onPayload":"ON","onPayloadType":"str","offPayload":"OFF","offPayloadType":"str","onlyWhenDark":false,"scheduleRndMax":0,"sunElevationThreshold":6,"sunShowElevationInStatus":false,"outputfreq":"output.statechange","x":120,"y":540,"wires":[["ef3f6ce7.056e9"]]},{"id":"c1f663ba.8a6d5","type":"api-call-service","z":"e273cd4b.ee175","name":"Arm Night Mode","server":"187051fc.e934be","version":1,"debugenabled":false,"service_domain":"elkm1","service":"alarm_arm_night_instant","entityId":"alarm_control_panel.home","data":"{\"code\":<removed>}","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":800,"y":500,"wires":[[]]},{"id":"ed532a0.0bf43d8","type":"api-call-service","z":"e273cd4b.ee175","name":"Disarm Night Mode","server":"187051fc.e934be","version":1,"debugenabled":false,"service_domain":"alarm_control_panel","service":"alarm_disarm","entityId":"alarm_control_panel.home","data":"{\"code\":<removed>}","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":810,"y":580,"wires":[[]]},{"id":"f085f2c8.bcbfb","type":"api-current-state","z":"e273cd4b.ee175","name":"Are We Home?","server":"187051fc.e934be","version":1,"outputs":2,"halt_if":"home","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"group.us","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":540,"y":500,"wires":[["c1f663ba.8a6d5"],[]]},{"id":"ef3f6ce7.056e9","type":"switch","z":"e273cd4b.ee175","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"ON","vt":"str"},{"t":"eq","v":"OFF","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":310,"y":540,"wires":[["f085f2c8.bcbfb"],["ccf68dba.b7e19"]]},{"id":"ccf68dba.b7e19","type":"api-current-state","z":"e273cd4b.ee175","name":"Alarm Armed?","server":"187051fc.e934be","version":1,"outputs":2,"halt_if":"armed_night","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"alarm_control_panel.home","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":540,"y":580,"wires":[["ed532a0.0bf43d8"],[]]},{"id":"5c626153.34a2d","type":"comment","z":"e273cd4b.ee175","name":"Arm Night Mode","info":"","x":120,"y":500,"wires":[]},{"id":"246f4de5.1a9b02","type":"light-scheduler-settings","z":"","name":"My Location","latitude":"${mylat}","longitude":"${mylon}"},{"id":"187051fc.e934be","type":"server","z":"","name":"Home Assistant","addon":true}]`

**Comment by mstarks01** [comment]
Oh, I should also mention I'm running HA Core 0.114.4 and OS version 4.12.

**Comment by gwww** [comment]
Need logs. Using HA the following in your config will turn them on:
```
logger:
  default: info
  logs:
    custom_components.elkm1: debug
    elkm1_lib: debug
```
Do your usual sequence only disarm right away to minimize log size.

If you wish, send a dropbox (or some other file sharing) link. My email is in the `pyproject.toml`.

**Comment by mstarks01** [comment]
Email sent.

**Comment by gwww** [comment]
Global option #40 was not set on the panel. This fixed the problem.

The documents on Home Assistant will be updated to include info on the Global Settings
