### ISSUE TITLE
Unable to Run basic REAME.md instructions

### ISSUE THREAD

**Issue by stevemcquaid** [gwww/elkm1#3]
When calling 
```
from elkm1_lib import Elk

elk = Elk({'url': 'elks://192.168.1.123', 'userid': 'user', 'password': 'password'})

elk.loop.run_until_complete(elk.connect())
elk.run()
```
The following error is received:

```
Traceback (most recent call last):
  File "./run.py", line 5, in <module>
    elk.loop.run_until_complete(elk.connect())
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 446, in run_until_complete
    future = tasks.ensure_future(future, loop=self)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 574, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
Task was destroyed but it is pending!
task: <Task pending coro=<Elk._connect() running at /usr/src/app/elkm1_lib/elk.py:46>>
/usr/local/lib/python3.5/asyncio/base_events.py:492: RuntimeWarning: coroutine 'Elk._connect' was never awaited
```

**Comment by stevemcquaid** [comment]
Dockerfile if interested in reproducing:

```FROM    python:3.5

RUN     apt-get update -y

RUN     apt-get install -y \
        python-serial \ 
        python3-serial

WORKDIR /usr/src/app

COPY    requirements.txt ./

RUN     pip install --no-cache-dir -r requirements.txt

COPY    . .

CMD     [ "python", "./run.py" ]
```

Simply add that do your base /elkm1 repo, and run the following:
`docker build -t stevemcquaid/elkm1:latest .`
`docker run -it stevemcquaid/elkm1:latest`

**Comment by gwww** [comment]
Try running one of the commands in the bin directory. I usually use the `elk` command. You can do something like: elk --url elk://IPADDRESS

I'll take a look at the README. It could be out of date as there's been a plethora of changes to the code over the last few weeks.

**Comment by stevemcquaid** [comment]
Thanks! Trying those now. 

Would you like a PR with the dockerfile + a few `make docker-build` `make docker-test` targets?

**Comment by gwww** [comment]
Docker file no required. New README.md pushed to github. Feel free to close if this works.

**Comment by stevemcquaid** [comment]
Unfortunately with the new changes it looks like it still hangs. 

```
Traceback (most recent call last):
  File "./run.py", line 7, in <module>
    elk.run()
  File "/usr/src/app/elkm1_lib/elk.py", line 122, in run
    self.loop.run_forever()
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1389, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.5/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
Task was destroyed but it is pending!
task: <Task pending coro=<Elk._connect() running at /usr/src/app/elkm1_lib/elk.py:64> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_connect_done(6)(), Task._wakeup()]>>
```

Seems to me to be indicative of an unsuccessful connect :(

**Comment by gwww** [comment]
Use the file `bin/simple` to start. Can't get to few lines of code to show off the lib :) You have to edit the IP address in it.

**Comment by stevemcquaid** [comment]
Thanks so much! The logging + elk.connect() fixed it for me!

Submitted PR #4 for ya if you'd like. Otherwise I can just include a link to the `bin/simple`

**Comment by gwww** [comment]
What was the problem (other than bad README :)

**Comment by stevemcquaid** [comment]
`elk.loop.run_until_complete(elk.connect())` -> `elk.connect()`

Did in fact fix it. Only issue was no output to STDOUT.
