### ISSUE TITLE
Can't install the lib elk_m1

### ISSUE THREAD

**Issue by srjacob999** [gwww/elkm1#34]
I am having problems installing the library.  When I enter this:
**pip install elkm1_lib**
I get the following output:
_Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting elkm1_lib
  Could not find a version that satisfies the requirement elkm1_lib (from versions: )
No matching distribution found for elkm1_lib_

**Comment by gwww** [comment]
Works for me.
```
% python3 -m venv venv
% source venv/bin/activate
% pip install elkm1_lib
Collecting elkm1_lib
  Using cached elkm1_lib-0.8.8-py3-none-any.whl (38 kB)
Collecting pyserial-asyncio<0.5.0,>=0.4.0
  Using cached pyserial_asyncio-0.4-py3-none-any.whl (7.1 kB)
Collecting pyserial
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Installing collected packages: pyserial, pyserial-asyncio, elkm1-lib
Successfully installed elkm1-lib-0.8.8 pyserial-3.5 pyserial-asyncio-0.4```

**Comment by srjacob999** [comment]
I didn't include the first 2 statements, which should be in the documentation

**Comment by gwww** [comment]
I think you are missing the point. The library installs in a clean environment. For whatever reason, that you need to figure out, your environment has a problem. Probably another library that conflicts.

**Comment by srjacob999** [comment]
Nope.  It installed fine for me.  Just needed the first two statements.  

However, I am running Samba.

What I want to do is put the library on my big Windows machine and work with it using the Microsoft IDE.  Then move it to the Pi.
