### ISSUE TITLE
Requirement is pinned for elkm1-lib 0.8.8: pyserial-asyncio>=0.4.0,<0.5.0

### ISSUE THREAD

**Issue by MartinHjelmare** [gwww/elkm1#37]
**Describe the bug**
- This library supports an integration in Home Assistant.
- The new pip resolver is more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**To Reproduce**

```sh
(home-assistant) x:~/dev/home-assistant/core$ pip install -r requirements_all.txt
...
(home-assistant) x:~/dev/home-assistant/core$ pipdeptree -w silence -r -p pyserial-asyncio
pyserial-asyncio==0.5
...
  - elkm1-lib==0.8.8 [requires: pyserial-asyncio>=0.4.0,<0.5.0]
...
```

**Expected behavior**
A peer compatible pinning strategy.

**Versions (please complete the following information):**
 - ElkM1 version: [0.8.8]
 - Home Assistant version: [2021.2.0.dev0]

**Comment by gwww** [comment]
My mistake. Change pushed.

**Comment by connectionjewelry** [comment]
www.connectionjewelry.com
