### ISSUE TITLE
[Enhancement] Know if a Zone can be bypassed

### ISSUE THREAD

**Issue by jimboca** [gwww/elkm1#38]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A property on a Zone to know if that Zone is bypassable.

**Describe alternatives you've considered**
I can't find if this information can be pulled from the ELK, but if possible I would like to know if the Zone can be bypassed.

**Additional context**

**Comment by gwww** [comment]
AFAIK there is no way to know if a zone can be bypassed. I just did a scan of the ElkM1 RS232 manual and nothing obvious is in there. I'd invite you to also take a look.

**Comment by jimboca** [comment]
Ok bummer. I did research but was hoping I missed something. Thanks for confirming.
