### ISSUE TITLE
[Enhancement] How to get F or C configuration from panel

### ISSUE THREAD

**Issue by jimboca** [gwww/elkm1#42]
**Is your feature request related to a problem? Please describe.**
The ua info is not parsed so users must configure F or C

**Describe the solution you'd like**
I read in the code what to do, but don't quite understand.

**Describe alternatives you've considered**
I can just force users to set F or C like the HA configuration has.

**Additional context**

**Comment by jimboca** [comment]
Also a related question that I can't find answer to.  Is there anyway to tell if the keypad has a temperature sensor?

**Comment by gwww** [comment]
I was reluctant to use the F/C from UA because the docs are so poor. F/C is a system setting and it didn't make sense to use the UA value which somehow seems to be user based (UA == User Access).

What we do in Home Assistant is C/F must be configured by the user of Home Assistant.

**Comment by jimboca** [comment]
Thanks, yes I saw HA has the user set it, I'll do the same.
