### ISSUE TITLE
[Enhancement] Tag releases on GitHub

### ISSUE THREAD

**Issue by dotlambda** [gwww/elkm1#43]
**Is your feature request related to a problem? Please describe.**
I want to download a release tarball that includes tests.

**Describe the solution you'd like**
Releases should appear on https://github.com/gwww/elkm1/releases.

**Describe alternatives you've considered**
Include `test/` in `MANIFEST.in`.

**Comment by mweinelt** [comment]
Became relevant again with the 1.2.0 update which is only available on PyPi, while GItHub is stuck on 1.0.0.

**Comment by gwww** [comment]
Done
