### ISSUE TITLE
pyserial-asyncio does blocking I/O in the event loop

### ISSUE THREAD

**Issue by bdraco** [gwww/elkm1#74]
https://github.com/gwww/elkm1/blob/d293364f15e09b70713a2db52752d031ca78f86f/pyproject.toml#L18

There is a replacement option that is fixed since pyserial-asyncio appears to be abandoned

https://github.com/home-assistant-libs/pyserial-asyncio-fast

**Comment by gwww** [comment]
Thanks! I had been hoping for a better maintained async serial lib! 

I will try to get this updated this week. This also applies to the UPB integration, for which I actively use serial IO and will be able to give it a proper test.

**Comment by gwww** [comment]
Fixed by https://github.com/gwww/elkm1/commit/2cac8096dcd674a59f68a3e252d1db987505317f
